version: "3.9"
services:
    minecraft:
      ports:
        - "25565:25565"
        # Uses a mount to save data upon docker-compose down
      volumes:
        - .:/minecraft
      environment:
        # EULA must be true to accept Minecrafts service agreement
        EULA : "TRUE"
      build: .
