version: "3.9"
services:
    flask_app:
      build: .
    flask_app2:
      build: .
    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./Users/edwincojitambo/Courses/302/flaskr/instance:/
        # changes to the directory of where the instance is on our laptop and call in where we want it on the flask container
      ports:
        - "5000:80"
