version: "3.9"
services:
    minecraft:
      ports:
        - "25565:25565"
      volumes:
        - ./data:/data
      environment:
        # EULA must be true to accept Minecrafts licensing agreement 
        EULA : "TRUE"
      build: .
